---
title: "Project management: How to effectively organize a project in R"
author: "Paul Regular and Keith Lewis"
date: "NAFC | Fisheries and Oceans Canada | October 26, 2017"
output: 
  ioslides_presentation:
    incremental: true
    widescreen: true
    logo: rproj.png
---


```{r setup, echo=FALSE, results="hide", message=FALSE, warning=FALSE}
knitr::opts_knit$set(root.dir = '../')
knitr::opts_chunk$set(cache = TRUE, 
                      fig.align = "center", 
                      fig.height = 4.5, 
                      fig.width = 7.5,
                      dev = "svg")
```

## Examples of what not to do!!!
- uncommented code; write for yourself 6 mo. from now
- long chunks of code
- all files in one folder
- don't use functions
- lots of versions of a file
- no metadata
- no documentation of file/folder structure
- cut/paste results into MS WORD
Note: may want to add screenshots of above
## Best practices
- uncommented code; write for yourself 6 mo. from now
- long chunks of code; split code into tasks
- all files in one folder; folder for similar file types
- don't use functions; use'em
- lots of versions of a file; version control
- no metadata; make metadata
- no documentation of file/folder structure; README files
- cut/paste results into MS WORD; use markdown

## Outline of next 4 weeks
use figure

## Objectives {.build}

- Introduce the concept of a Research Compendium
- Demonstrate the set-up and workflow of a compendium
- Give a brief teaser of git and Rmarkdown

## Research Compendium

- What is it?
    - A compendium is a convention for how to organize key files for a project (data, code, text, etc.) into directories
- Why use one?
    - Simplifies file management
    - Streamlines analytical workflows
    - More efficient for you, future you and your collaborators
    - Reproducible and extensible


## Exercises
- Create a project folder and an RProj
- Add subfolders
- Write a script to:
  - subset some data
  - make some figures
  - save to a folder
## References

- This presentation was heavily based on this really useful doc: https://github.com/ropensci/rrrpkg
- For more details on building R packages, see: [Wickham, Hadley, R Packages: Organise, test, document, and share your code. O’Reilly.](http://r-pkgs.had.co.nz/)

